import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));

/**
 * Stamp the source manifest with a dev-suffixed version for the test vault
 * so every build looks like a fresh version to Obsidian's plugin loader —
 * defeats stale-module caching during manual QA. Source manifest.json is
 * NEVER modified; the canonical version stays the GitHub release version.
 * Format: `${baseVersion}-dev.${YYYYMMDD-HHmm}`.
 */
function stampManifestForVault() {
	const stamp = new Date()
		.toISOString()
		.slice(0, 16)
		.replace(/[-:]/g, "")
		.replace("T", "-");
	return { ...manifest, version: `${manifest.version}-dev.${stamp}` };
}

// In prod, esbuild emits build/main.js + build/styles.css. This plugin copies
// manifest.json alongside them and — when DEPLOY_VAULT=1 — mirrors the build
// into the in-repo test vault for manual QA. Default OFF so CI never trips on
// a missing vault.
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (!prod) return;

			mkdirSync("build", { recursive: true });
			copyFileSync("manifest.json", "build/manifest.json");

			if (process.env.DEPLOY_VAULT) {
				const VAULT_PLUGIN_DIR =
					"test/NewTab/.obsidian/plugins/newtab";
				if (existsSync("test/NewTab/.obsidian")) {
					mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
					copyFileSync("build/main.js", `${VAULT_PLUGIN_DIR}/main.js`);
					copyFileSync(
						"build/styles.css",
						`${VAULT_PLUGIN_DIR}/styles.css`,
					);
					const stampedManifest = stampManifestForVault();
					writeFileSync(
						`${VAULT_PLUGIN_DIR}/manifest.json`,
						JSON.stringify(stampedManifest, null, "\t") + "\n",
						"utf8",
					);
					console.log(
						`[deploy] Plugin copied to ${VAULT_PLUGIN_DIR} (version: ${stampedManifest.version})`,
					);
				} else {
					console.warn(
						"[deploy] DEPLOY_VAULT set but test/NewTab/.obsidian missing — skipped",
					);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts", "styles.scss"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	jsx: "automatic",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir,
	minify: prod,
	plugins: [sassPlugin(), copyAssets],
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
		"process.env.EMULATE_MOBILE": prod
			? "false"
			: process.argv.includes("--mobile").toString(),
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
